portfolio/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
path('admin/', admin.site.urls),
#connect path to portfolio_app urls
path('', include('portfolio_app.urls')),
]

portfolio/portfolio_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
#path function defines a url pattern
#'' is empty to represent based path to app
# views.index is the function defined in views.py
# name='index' parameter is to dynamically create url
# example in html <a href="{% url 'index' %}">Home</a>.
path('', views.index, name='index'),
path('students/', views.StudentListView.as_view(), name= 'students'),
path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
path('student/<str:pk>/update_portfolio/', views.updatePortfolio, name='update_portfolio'),
path('portfolios/', views.PortfolioListView.as_view(), name= 'portfolios'),
path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name='portfolio-detail'),
path('projects/', views.ProjectListView.as_view(), name= 'projects'),
path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project-detail'),
path('portfolio/<int:portfolio_id>/create_project/', views.createProject, name='create_project'),
path('portfolio/<str:pk>/update_project/', views.updateProject, name='update_project'),
path('portfolio/<str:pk>/deleteproject/', views.deleteProject, name='delete_project'),


]

portfolio/portfolio_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Student(models.Model):

    # List choices for Major value in database, human readable name
    MAJOR = (
        ('CSCI-BS', 'BS in Computer Science'),
        ('CPEN-BS', 'BS in Computer Engineering'),
        ('BIGD-BI', 'BI in Game Design and Development'),
        ('BICS-BI', 'BI in Computer Science'),
        ('BISC-BI', 'BI in Computer Security'),
        ('CSCI-BA', 'BA in Computer Science'),
        ('DASE-BS', 'BS in Data Analytics and Software Engineering'),          
    )
    name = models.CharField(max_length=200)
    email = models.EmailField("UCCS Email", max_length=200)
    major = models.CharField(max_length=200, choices=MAJOR)  
    portfolio = models.OneToOneField('Portfolio' ,on_delete=models.CASCADE, unique=True)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("student-detail", args=[str(self.id)])
    
   

class Portfolio(models.Model):
    title = models.CharField(max_length=200)
    contact_email = models.EmailField("Contact Email", max_length=200)
    is_active = models.BooleanField(default=False)
    about = models.TextField(blank=True)

    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("portfolio-detail", args=[str(self.id)])
    
class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    portfolio = models.ForeignKey('Portfolio', on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("project-detail", args=[str(self.id)])
    
'''
class ProjectsInPortfolio(models.Model):
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
  
class Meta:
    unique_together = ('project', 'portfolio')
'''

portfolio/portfolio_app/forms.py
from django.forms import ModelForm
from .models import Project, Portfolio

# Create the class for the project form
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields =('title', 'description')

class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'

portfolio/portfolio_app/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from .models import Student, Project, Portfolio
from .forms import ProjectForm, PortfolioForm
# Create your views here.



class StudentListView(generic.ListView):
    model = Student
    
class StudentDetailView(generic.DetailView):
    model = Student

class PortfolioListView(generic.ListView):
    model = Portfolio

class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = 'portfolio_app/portfolio_detail.html'  # Specify the template name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        portfolio = self.get_object()  # Retrieve the portfolio object
        projects = Project.objects.filter(portfolio=portfolio)  # Retrieve associated projects
        context['projects'] = projects  # Pass projects to the context
        return context

def createProject(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id) 
    print("portfolio", portfolio.id)
    form = ProjectForm()
    if request.method == 'POST':
        # Create a new dictionary with form data and portfolio_id
        project_data = request.POST.copy()
        project_data['portfolio_id'] = portfolio_id
        
        form = ProjectForm(project_data)
        if form.is_valid():
            # Save the form without committing to the database
            project = form.save(commit=False)
            # Set the portfolio relationship
            project.portfolio = portfolio
            project.save()

            # Redirect back to the portfolio detail page
            return redirect('portfolio-detail', portfolio_id)

    context = {'form': form}
   
    return render(request, 'portfolio_app/project_form.html', context)



def deleteProject(request, pk):
    project = get_object_or_404(Project, pk=pk)
    portfolio_id = project.portfolio.id 
    if request.method == 'POST':
        project.delete()
        return redirect('portfolio-detail', portfolio_id)
    context = {'project': project, 'portfolio_id': portfolio_id}  # Add 'portfolio_id' to the context
    return render(request, 'portfolio_app/delete_project.html', context)


def updateProject(request, pk):
    #portfolio = Portfolio.objects.get(pk=portfolio_id) 
    project = get_object_or_404(Project, pk=pk)
    form = ProjectForm(instance=project)
    portfolio_id = project.portfolio.id
    if request.method == 'POST':
        # Create a new dictionary with form data and portfolio_id
        project_data = request.POST.copy()
        project_data['portfolio_id'] = portfolio_id
        form = ProjectForm(project_data, instance=project)
        if form.is_valid():
            # Save the form without committing to the database
            project = form.save(commit=False)
            project.save()
            # Redirect back to the portfolio detail page
            return redirect('portfolio-detail', portfolio_id)
    context = {'form': form} 
    return render(request, 'portfolio_app/project_form.html', context)

def updatePortfolio(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)
    form = PortfolioForm(instance=portfolio)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, instance=portfolio)
        if form.is_valid():
            portfolio = form.save()
            # Assuming you have a relation to a student in your Portfolio model
            return redirect('student-detail', portfolio.student.pk)
    context = {'form': form} 
    return render(request, 'portfolio_app/portfolio_form.html', context)

class ProjectListView(generic.ListView):
    model = Project

class ProjectDetailView(generic.DetailView):
    model = Project


  
def index(request):
    student_active_portfolios = Student.objects.select_related('portfolio').all().filter(portfolio__is_active=True)
    print("active portfolio query set", student_active_portfolios)
    return render( request, 'portfolio_app/index.html', {'student_active_portfolios':student_active_portfolios})

portfolio/portfolio_app/templates/portfolio_app/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light" >
  <head>
    <title>UCCS CS Students</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


  </head>

  <body>
    <div class="container-fluid">
      <!-- Dark Mode Toggle Button -->
      <button class="btn btn-dark" id="darkModeToggle" onclick="toggleDarkMode()">Toggle Dark Mode</button>

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <img src="{% static 'images/uccs_logo.gif' %}" />
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
          data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'students' %}">Students</a>
              </li>
              <li class="nav-item">
                <a class "nav-link" href="#">Menu 2</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- add block content from html template -->
      {% block content %}
      {% endblock %}
    </div>

    <script>
      const toggleDarkMode = () => {
        const htmlElement = document.documentElement;
        if (htmlElement.dataset.bsTheme === "light") {
          htmlElement.dataset.bsTheme = "dark";
        } else {
          htmlElement.dataset.bsTheme = "light";
        }
      };
    </script>
  </body>
</html>

portfolio/portfolio_app/templates/portfolio_app/delete_project.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
  <div class="row ">
    <div class="col-md-6">
      <div class="card card-body >
        <h1>Are you Sure</h1>
        <form action="{% url 'delete_project' project.pk %}" method="POST">
          {% csrf_token %}
          <input class="btn btn-danger text-uppercase" type="submit" name="confirm" value="Confirm" class="" />
          <a class="btn btn-primary text-uppercase" href="{% url 'portfolio-detail' portfolio_id %}">cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/index.html
<!-- inherit from base.html -->
{% extends 'portfolio_app/base_template.html' %}

<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Computer Science Student Portfolios</h1>

<h2>List of Students with Active Portfolios</h2>
<ul class="list-group">
{% for i in student_active_portfolios %}
<li class="list-group-item">Name: {{i.name}}
<p><strong>Portfolio:</strong>{{ i.portfolio.title }}</p>
<a class="btn btn-primary" href="{{ i.portfolio.get_absolute_url }}" role="button">View</a>
</li>
{% endfor %}
</ul>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/portfolio_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
  <h1>Portfolio Title: {{ portfolio.title }}</h1>
  <p>
    <b>Portfolio Title:</b> {{ portfolio.contact_email }}<br />
    <b>About:</b>{{ portfolio.about }}
  </p>

  <h2>Project List</h2>
  <a class="btn btn-primary" href="{% url 'create_project' portfolio.id %}" role="button">New</a>

  <div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 gy-2 p-3">
      {% for project in projects %}
        <div class="col">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1547190027-9156686aa2f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhhY2tlcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=700&q=60" alt="Card image" style="width:100%" />

          <div class="input-group mb-3">
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">{{ project.title }}</button>
            <ul class="dropdown-menu">
              <li>
                <a class="btn btn-primary px-4" href="{{ project.get_absolute_url }}" role="button">View</a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a class="btn btn-secondary" href="{% url 'update_project' project.pk %}">Update Project</a>
              </li>
              <li>
                <a class="btn btn-danger" href="{% url 'delete_project' project.pk %}" role="button">Delete Project</a>
              </li>
            </ul>
            <input type="text" class="form-control" aria-label="Text input with dropdown button" />
          </div>
        </div>
        {% empty %}
        <p>There are no projects.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/portfolio_form.html
<!-- inherit from base.html -->
{% extends 'portfolio_app/base_template.html' %}


<!-- Replace block content in base_template.html -->
{% block content %}

  <form action="" method="POST">
    {% csrf_token %}
    <table >{{ form.as_table }}</table>
    <input type="submit" name="Submit" />
  </form>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/portfolio_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>projects List</h1>
{% comment %} {% if student_list %} {% endcomment %}
<ul>
{% for portfolio in portfolio_list %}
<li>
<a href="{{ portfolio.get_absolute_url }}">{{ portfolio.title }}</a>
</li>
{%empty%}
<p>There are no projects registered.</p>
{% endfor %}
</ul>




{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Portfolio Title: {{project.title }}</h1>
<p><b>Portfolio Title:</b> {{project.description }}<br>
<b>About: </b>{{project.about }}</p>

<strong>Portfolio: </strong>
{% for project in project_list %}
    <p>{{ project.title }}</p>
    <p>{{ project.description }}</p>
    <p>{{ project.portfolio }}</p>
{% endfor %}



{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_form.html
<!-- inherit from base.html -->
{% extends 'portfolio_app/base_template.html' %}
{% block content %}

  <form action="" method="POST">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" name="Submit" />
  </form>
{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/project_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Projects In Portfolio</h1>
{% comment %} {% if student_list %} {% endcomment %}
<ul>
    {% for project in project_list %}
<li>
<a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
</li>
<li>{{ project.description }}</li>
<li>{{ project.portfolio }}</li>
{%empty%}
<p>There are no projects registered.</p>
{% endfor %}

</ul>

{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/student_detail.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Student Name: {{ student.name }}</h1>

<p><strong>Email:</strong> {{ student.email }}<br>
<strong>Major:</strong> {{ student.major }}<br>
<strong>Portfolio: <a href="{{ student.portfolio.get_absolute_url }}">{{ student.portfolio.title }} </a>
    <a class="btn btn-primary"href="{% url 'update_portfolio'  pk=student.pk %}">Update Portfolio</a>

{% endblock %}

portfolio/portfolio_app/templates/portfolio_app/student_list.html
{% extends 'portfolio_app/base_template.html' %}

{% block content %}
<h1>Student List</h1>
{% comment %} {% if student_list %} {% endcomment %}
<ul>
{% for student in student_list %}
<li>
<a href="{{ student.get_absolute_url }}">{{ student.name }}</a>
</li>
{%empty%}
<p>There are no students registered.</p>
{% endfor %}
</ul>

{% endblock %}